apiVersion: v1
kind: ReplicationController
metadata:
  name: kubetest
spec:
  replicas: 3
  selector:
    app: kubetest
  template:
    metadata:
      labels:
        app: kubetest
    spec:
      containers:
      - image: kubetest:v1
        name: kubetest
        livenessProbe:
          httpGet:
            path: /up
            port: 80
        ports:
        - containerPort: 80
          protocol: TCP
