apiVersion: v1
kind: Service
metadata:
  name: kubetest
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 433
    targetPort: 8443
  selector:
    app: kubetest
