apiVersion: v1
kind: Pod
metadata:
  name: kubetest
  labels:
    env: prod
spec:
  containers:
  - image: kubetest:v1
    name: kubetest
    livenessProbe:
      httpGet:
        path: /up
        port: 80
    ports:
    - containerPort: 80
      protocol: TCP
