apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubetest
  labels:
    app: kubetest
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubetest
  template:
    metadata:
      labels:
        app: kubetest
    spec:
      containers:
      - image: kubetest:v1
        name: kubetest
        livenessProbe:
          httpGet:
            path: /up
            port: 80
        ports:
        - containerPort: 80
          protocol: TCP
